
javascripts:
  - 'lib/jquery.js'
  - 'lib/jquery-ui.js'
  - 'lib/underscore.js'
  - 'lib/backbone.js'
  - 'lib/coffeescript.js'
  - 'lib/less.js'
  - 'lib/strophe.js'
  - 'lib/timeago.js'
  - 'lib/md5.js'
  - 'app/controllers/*.coffee'
  - 'app/views/**/*.coffee'
  - 'app/models/*.coffee'

stylesheets:
  - 'public/stylesheets/*.css'
  - 'public/stylesheets/*.less'
